eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    hostname: clientName
    prefer-ip-address: true
spring:
  application:
    name: client
